In [ ]:
from tkinter import *
root=Tk()
root.title('Simple Calculator')
mainframe=Frame(root,width=45,bd=10, relief=RIDGE,bg='orange')
mainframe.pack()
inner=Frame(root,width=45,bd=10,relief=RIDGE,bg='cyan')
inner.pack()
e=Entry(inner,width=65,borderwidth=5)
e.grid(row=0,column=0,columnspan=4,padx=10,pady=1)
def onclick(num):
    x=e.get()
    e.delete(0,END)
    e.insert(0,str(x)+str(num))

def clear():
    e.delete(0,END)

def add():
    global first,op
    op='+'
    first=e.get()
    e.delete(0,END)

def sub():
    global first,op
    op='-'
    first=e.get()
    e.delete(0,END)

def mul():
    global first,op
    op='*'
    first=e.get()
    e.delete(0,END)

def div():
    global first,op
    op='/'
    first=e.get()
    e.delete(0,END)

def equal():
    second=e.get()
    if op=='+':
        result=float(first)+float(second)
    elif op=='-':
        result=float(first)-float(second)
    elif op=='*':
        result=float(first)*float(second)
    elif op=='/':
        result=float(first)/float(second)
    e.delete(0,END)
    e.insert(0,result)

button_1=Button(inner,text='1',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(1))

button_2=Button(inner,text='2',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(2))

button_3=Button(inner,text='3',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(3))

button_4=Button(inner,text='4',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(4))

button_5=Button(inner,text='5',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(5))

button_6=Button(inner,text='6',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(6))

button_7=Button(inner,text='7',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(7))

button_8=Button(inner,text='8',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(8))

button_9=Button(inner,text='9',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(9))

button_0=Button(inner,text='0',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(0))

button_add=Button(inner,text='+',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=add)
button_sub=Button(inner,text='-',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=sub)
button_mul=Button(inner,text='*',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=mul)
button_div=Button(inner,text='/',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=div)
button_equal=Button(inner,text='=',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=equal)
button_clear=Button(inner,text='C',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=clear)

button_1.grid(row=3,column=0)
button_2.grid(row=3,column=1)
button_3.grid(row=3,column=2)
button_4.grid(row=2,column=0)
button_5.grid(row=2,column=1)
button_6.grid(row=2,column=2)
button_7.grid(row=1,column=0)
button_8.grid(row=1,column=1)
button_9.grid(row=1,column=2)
button_0.grid(row=4,column=0)
button_add.grid(row=1,column=3)
button_sub.grid(row=2,column=3)
button_mul.grid(row=3,column=3)
button_div.grid(row=4,column=3)
button_equal.grid(row=4,column=2)
button_clear.grid(row=4,column=1)
root.mainloop()

In [1]:
a=[i for i in range(10000000)]
b=a=[i for i in range(10000000,20000000)]

c=[]
import time

start =time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

4.949604272842407


In [2]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start =time.time()
c=a+b
print(time.time()-start)

0.2638378143310547


In [1]:
4.949604272842407/0.2638378143310547

18.76002606143414

In [2]:
a=[i for i in range(100000)]
import sys

sys.getsizeof(a)

800984

In [ ]:
import numpy as np
a=np.arange(100000,dtype=np.int16)
sys.getsizeof(a)

: 

In [1]:
#2D and 3D
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [1]:
print('hey')

hey


In [3]:
#dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
import numpy as np
np.ones((3,4))

In [3]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [1]:
#RANDOM VALUE IN BETWEEN 0-1
import numpy as np
np.random.random((3,4))

array([[0.82625259, 0.03094895, 0.07428161, 0.1766012 ],
       [0.31774231, 0.78417453, 0.81363711, 0.47120987],
       [0.64232173, 0.42729512, 0.78482267, 0.05405807]])

In [3]:
#RANDOM VALUE IN BETWEEN 0-1
import numpy as np
np.random.random((300,400))

array([[0.13863831, 0.26504405, 0.87641748, ..., 0.66623646, 0.12312816,
        0.86776825],
       [0.70888942, 0.95350697, 0.62515229, ..., 0.75607052, 0.60973787,
        0.0307085 ],
       [0.49676669, 0.89334276, 0.17107289, ..., 0.76839307, 0.00756799,
        0.83359798],
       ...,
       [0.55826459, 0.90010454, 0.75569888, ..., 0.53265882, 0.29407207,
        0.65213189],
       [0.93556095, 0.26477731, 0.41126615, ..., 0.6556379 , 0.55262346,
        0.19305945],
       [0.81594455, 0.54296745, 0.84301739, ..., 0.87607269, 0.25066581,
        0.26827722]])

In [4]:
a1 = np.arange(10,dtype=np.int64)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(12,dtype=np.int64).reshape(2,2,3)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a1 = np.arange(10,dtype=np.int64)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(12,dtype=np.int64).reshape(2,2,3)

a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [6]:
a1 = np.arange(10,dtype=np.int64)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(12,dtype=np.int64).reshape(2,2,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [7]:
#ndim
a3.ndim

3

In [8]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [9]:
print(a3.size)
a3

12


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [10]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [11]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a2)
a1

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[47., 59., 89.],
       [61., 69., 72.],
       [13.,  9., 92.]])

In [15]:
np.prod(a1)

805053954223584.0

In [19]:
#max/min/sum/prod
#0 -> col and 1 -> row
np.max(a1,axis=0)

array([61., 69., 92.])

In [20]:
np.min(a1,axis=0)

array([13.,  9., 72.])

In [21]:
np.prod(a1,axis=0)

array([ 37271.,  36639., 589536.])

In [22]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
a1[1]

1

In [24]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
a3[1,0,1]

5

In [27]:
a3[1,1,0]

6

In [28]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a1[2:5:2]

array([2, 4])

In [30]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [34]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [36]:
print('hey')

hey


In [37]:
print('day2')

day2


In [38]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[82., 96., 13.],
       [29., 99., 93.],
       [66., 30., 82.]])

In [5]:
import numpy as np 
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(36).reshape(3,3,4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [6]:
a3[1,1:,1::2]

array([[17, 19],
       [21, 23]])

In [7]:
a3[1,2,2]

22

In [46]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(120).reshape(10,3,4)
a3

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[ 24,  25,  26,  27],
        [ 28,  29,  30,  31],
        [ 32,  33,  34,  35]],

       [[ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59]],

       [[ 60,  61,  62,  63],
        [ 64,  65,  66,  67],
        [ 68,  69,  70,  71]],

       [[ 72,  73,  74,  75],
        [ 76,  77,  78,  79],
        [ 80,  81,  82,  83]],

       [[ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95]],

       [[ 96,  97,  98,  99],
        [100, 101, 102, 103],
        [104, 105, 106, 107]],

       [[108, 109, 110, 111],
        [112, 113, 114, 115],
        [116, 117, 118, 119]]])

In [8]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a2[0:2,1::2]    

array([[1, 3],
       [5, 7]])

In [10]:
a2[1:,0:2]

array([[4, 5],
       [8, 9]])

In [11]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [13]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [21]:
#if i want [0 2 18 20]
a3[::2,0,::2]
#before first comma,
#[::2] selects the matrices
#[0] gives rows
#[::2] selects the elements

array([[ 0,  2],
       [18, 20]])

In [23]:
#if i want [[22,23],[25,26]]
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [22]:
#if i want [[9,11],[15,17]]
a3[1,::2,::2]

array([[ 9, 11],
       [15, 17]])

In [25]:

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
#if i want [[10,16],[19,25]]
a3[1:,::2,1]

array([[10, 16],
       [19, 25]])

In [29]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [2]:
import numpy as np 
import pandas as pd
country =  ['India','Pakistan','USA','Nepal']
pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
dtype: object

In [3]:
marks = [67,57,89,100]
subjects = ['maths','English','chem','Physics']
pd.Series(marks,index=subjects)

maths       67
English     57
chem        89
Physics    100
dtype: int64

In [5]:
marks = {
    'maths':67,
    'English':57,
    'chem':89,
    'Physics':100
}

marks_series = pd.Series(marks,name='Tom Holland')
marks_series

maths       67
English     57
chem        89
Physics    100
Name: Tom Holland, dtype: int64

In [6]:
print('hey')

hey


In [10]:
#with one col
subs = pd.read_csv('/content/ipl-matches(1).csv',squeeze=True)
subs

/tmp/ipykernel_51708/4041689178.py:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  subs = pd.read_csv('/content/ipl-matches(1).csv',squeeze=True)


FileNotFoundError: [Errno 2] No such file or directory: '/content/ipl-matches(1).csv'